name: CI/CD Pipeline

on:
  push:
    branches: 
      - main # main 브랜치에 push될 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm install
        working-directory: shooking-shop

      - name: Git user 설정
        run: |
          git config --global user.name "lsa0828"
          git config --global user.email "lsa0828@duksung.ac.kr"

      - name: gh-pages용 빌드 및 배포
        run: npm run deploy
        working-directory: shooking-shop

      - name: 배포 완료 메시지
        run: echo "React 앱이 GitHub Pages에 성공적으로 배포되었습니다."
